"""empty message

Revision ID: 0bba7c476ca8
Revises: 
Create Date: 2023-09-13 20:42:48.878770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bba7c476ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_table',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('names', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('club',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('clubName', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('motto', sa.String(length=500), nullable=True),
    sa.Column('mission', sa.String(length=500), nullable=True),
    sa.Column('vision', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('division', sa.String(length=1000), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('scout',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('names', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('isActivated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('player',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('names', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('height', sa.String(length=5), nullable=True),
    sa.Column('weight', sa.String(length=5), nullable=True),
    sa.Column('playerSince', sa.String(length=5000), nullable=True),
    sa.Column('nationalAppearance', sa.String(length=5), nullable=True),
    sa.Column('clubAppearance', sa.String(length=5), nullable=True),
    sa.Column('goals', sa.String(length=5), nullable=True),
    sa.Column('assist', sa.String(length=5), nullable=True),
    sa.Column('highLight', sa.String(length=2000), nullable=True),
    sa.Column('achievement', sa.String(length=5000), nullable=True),
    sa.Column('scout_email', sa.String(length=100), nullable=True),
    sa.Column('isActivated', sa.Boolean(), nullable=True),
    sa.Column('isOnMarket', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scout_email'], ['scout.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('highLights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('uploadDate', sa.Date(), nullable=True),
    sa.Column('player_email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['player_email'], ['player.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playerTest',
    sa.Column('testId', sa.String(length=200), nullable=False),
    sa.Column('medicalTest', sa.String(length=3), nullable=True),
    sa.Column('physicalTest', sa.String(length=3), nullable=True),
    sa.Column('testPass', sa.Boolean(), nullable=True),
    sa.Column('player_email', sa.String(length=100), nullable=True),
    sa.Column('club_email', sa.String(length=100), nullable=True),
    sa.Column('createdDate', sa.Date(), nullable=True),
    sa.Column('scout_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('documentName', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['club_email'], ['club.email'], ),
    sa.ForeignKeyConstraint(['player_email'], ['player.email'], ),
    sa.ForeignKeyConstraint(['scout_email'], ['scout.email'], ),
    sa.PrimaryKeyConstraint('testId')
    )
    op.create_table('post_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('player_email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['player_email'], ['player.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priceTag',
    sa.Column('tagId', sa.Integer(), nullable=False),
    sa.Column('priceTag', sa.Float(), nullable=True),
    sa.Column('scoutShare', sa.Float(), nullable=True),
    sa.Column('playerShare', sa.Float(), nullable=True),
    sa.Column('teamShare', sa.Float(), nullable=True),
    sa.Column('playerEmail', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['playerEmail'], ['player.email'], ),
    sa.PrimaryKeyConstraint('tagId'),
    sa.UniqueConstraint('playerEmail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('priceTag')
    op.drop_table('post_photos')
    op.drop_table('playerTest')
    op.drop_table('highLights')
    op.drop_table('player')
    op.drop_table('scout')
    op.drop_table('club')
    op.drop_table('admin_table')
    # ### end Alembic commands ###
